name: Make sure Elixir code is formatted 

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: supersimple/mix-format@v1
      with:
        elixir_version: "1.15"
        otp_version: "26"
        mix_env: "dev"